[workspace]
resolver = "2"

members = [ "increase_target_staked_ratio",
    "phase2",
    "phase3",
    "pre-phase4",
    "phase4",
    "phase5",
    "increase_target_staked_ratio",
    "update-tx-claim-rewards",
]

default-members = [
    "phase2",
    "phase3",
    "pre-phase4",
    "phase4",
    "phase5",
    "increase_target_staked_ratio",
    "update-tx-claim-rewards",
]

[workspace.package]
authors = ["Heliax AG <hello@heliax.dev>"]
edition = "2021"
license = "GPL-3.0"
version = "0.1.0"

[workspace.dependencies]
namada_tx_prelude = { git = "https://github.com/anoma/namada", rev = "66e512225da9c5f13d9e23647cf9c07ab987f1eb" }
namada_proof_of_stake = { git = "https://github.com/anoma/namada", rev = "66e512225da9c5f13d9e23647cf9c07ab987f1eb" }
namada_ibc = { git = "https://github.com/anoma/namada", rev = "66e512225da9c5f13d9e23647cf9c07ab987f1eb" }
rlsf = "0.2.1"
getrandom = { version = "0.2", features = ["custom"] }
lazy_static = "1.4.0"

[profile.release]
lto = true
panic = "abort"
opt-level = 'z'
strip = "debuginfo"
